version: '3'
services:
  caddy:
    image: ghcr.io/thereallorenz/caddy-docker-cloudflare:0.3.0
    container_name: caddy
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}
      CADDY_INGRESS_NETWORKS: caddy
    networks:
      - caddy
    restart: unless-stopped

networks:
  caddy:
    external: true
